# Generated by Django 5.1.4 on 2024-12-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi')], max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('watch_link', models.URLField()),
                ('trailer_link', models.URLField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
