# Generated by Django 5.1.4 on 2024-12-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, upload_to='movie_thumbnails/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
