# Generated by Django 5.1.4 on 2024-12-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi')], default='action', max_length=50),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
