# Generated by Django 5.1.4 on 2024-12-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_genre_remove_movie_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
